# Generated by Django 5.1.5 on 2025-02-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_imagemodel_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
