# Generated by Django 5.1.5 on 2025-05-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_book_category_course_interesting_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesting',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='interesting/cover/'),
        ),
    ]
