# Generated by Django 5.1.5 on 2025-05-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_interesting_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, help_text='Путь для фронта (например: programming, eng-basic)', max_length=100, null=True, unique=True),
        ),
    ]
