name: Trigger Deployment on Push

on:
  push:
    branches:
      - main

jobs:
  call-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy repo via repository_dispatch
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/lantemir/nsinvest-deploy/dispatches \
            -d '{"event_type": "deploy_triggered_from_backend"}'